# Generated by Django 4.2.7 on 2023-12-27 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_rename_client_mailing_clients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='client',
        ),
    ]
